business/urls.py
from django.urls import path
from . import views


urlpatterns=[
    # path('',views.dashboard, name='bus.dashboard'),
    path('dashboard/',views.dashboard, name='bus.dashboard'),
    path('profile/',views.profile, name='bus.profile'),
    path('options/',views.options, name='bus.options'),
    path('options/<str:type>/',views.options, name='bus.options'),
    path('photos/',views.photos, name='bus.photos'),
    path('services/',views.services, name='bus.services'),
    path('services/<int:pk>/update',views.updateService, name='bus.services.update'),
    path('services/<int:pk>/delete',views.deleteService, name='bus.services.delete'),
    path('staff',views.staff, name='bus.staff'),
    path('staff/<int:pk>/update',views.updateStaff, name='bus.staff.update'),
    path('staff/<int:pk>/delete',views.deleteStaff, name='bus.staff.delete'),
]

services/urls.py
from provider import views
from django.urls import path


urlpatterns = [
     path('register/',views.register, name='register'), 
]

staner/urls.py
import business
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('bus/', include('business.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business/models.py
from django.db import models
import uuid
from accounts.models import User
from services.models import Service as StanarServices
# Create your models here.

class Business(models.Model):
    user     = models.OneToOneField(User, on_delete=models.CASCADE, null=True,blank=True)
    business_name     = models.CharField(max_length=100)
    business_phone    = models.CharField(max_length=100)
    business_email    = models.EmailField(max_length=100)
    business_bio      = models.TextField(blank=True)
    instagram_link    = models.CharField(max_length=100, blank=True,null= True)
    facebook_link     = models.CharField(max_length=100, blank=True,null= True)
    twitter_link      = models.CharField(max_length=100, blank=True,null= True)
    website           = models.CharField(max_length=100, blank=True,null= True)
    postcode = models.CharField(max_length=100)
    address_line_1  = models.CharField(max_length=200)
    address_line_2  = models.CharField(max_length=200, blank=True,null= True)
    town  = models.CharField(max_length=100)
    country     = models.CharField(max_length=100)
    id       = models.UUIDField(default=uuid.uuid4,unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return self.business_name

class Amenities(models.Model):
    business        = models.OneToOneField(Business, on_delete=models.CASCADE, null=True,blank=True)
    cus_parking     = models.CharField(max_length=10,default='off',blank=True,null= True)
    card_accept     = models.CharField(max_length=10,default='off',blank=True,null= True)
    disability      = models.CharField(max_length=10,default='off',blank=True,null= True)
    child_friendly  = models.CharField(max_length=10,default='off',blank=True,null= True)
    pet_friendly    = models.CharField(max_length=10,default='off',blank=True,null= True)
    wifi            = models.CharField(max_length=10,default='off',blank=True,null= True)
    loyalty_program = models.CharField(max_length=10,default='off',blank=True,null= True)
    
    def __str__(self) -> str:
        return self.business

class PaymentMethods(models.Model):
    business        = models.OneToOneField(Business, on_delete=models.CASCADE, null=True,blank=True)
    cash            = models.CharField(max_length=10,default='off',blank=True,null= True)
    physical        = models.CharField(max_length=10,default='off',blank=True,null= True)
    check           = models.CharField(max_length=10,default='off',blank=True,null= True)
    paypal          = models.CharField(max_length=10,default='off',blank=True,null= True)
    bank_transfer   = models.CharField(max_length=10,default='off',blank=True,null= True)
    gift_card       = models.CharField(max_length=10,default='off',blank=True,null= True)
    
    def __str__(self) -> str:
        return self.business

class Photos(models.Model):
    business        = models.OneToOneField(Business, on_delete=models.CASCADE, null=True,blank=True)
    logo            = models.ImageField(null=True,blank=True, default="stanar-logo-placeholder.jpg")
    banner          = models.ImageField(null=True,blank=True, default="stanar-banner-placeholder.jpg")
    display_1       = models.ImageField(null=True,blank=True, default="stanar-display-placeholder.jpg")
    display_2       = models.ImageField(null=True,blank=True, default="stanar-display-placeholder.jpg")
    display_3       = models.ImageField(null=True,blank=True, default="stanar-display-placeholder.jpg")
    display_4       = models.ImageField(null=True,blank=True, default="stanar-display-placeholder.jpg")
    
    def __str__(self) -> str:
        return self.business

class Service(models.Model):
    business = models.ForeignKey(Business,null=True,blank=True,on_delete=models.CASCADE)
    duration_hours = models.CharField(max_length=2,blank=True,null=True,default='00')
    duration_mins  = models.CharField(max_length=2,blank=True,null=True,default='00')
    price   = models.FloatField(default=0.00)
    note    = models.TextField(max_length=300, blank=True,null=True)
    service =models.ForeignKey(StanarServices,on_delete=models.CASCADE,null=True)

    def __str__(self) -> str:
        return self.business

class Staff(models.Model):
    business =models.ForeignKey(Business,on_delete=models.CASCADE, null=True,blank=True)
    user    = models.OneToOneField(User, on_delete=models.CASCADE, null=True,blank=True)
    id       = models.UUIDField(default=uuid.uuid4,unique=True, primary_key=True, editable=False)

class StaffService(models.Model):
    staff = models.ForeignKey(Staff,on_delete=models.CASCADE, null=True,blank=True)
    service  = models.ForeignKey(Service, on_delete=models.CASCADE, null=True,blank=True)
    is_active = models.BooleanField(default=True)

services/models.py
from django.db import models
import uuid

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True,editable=False)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name

class Service(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,primary_key=True,editable=False)
    name = models.CharField(max_length=200)
    sub_category= models.BooleanField(default=False,null=True,blank=True)
    category_id = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

business/views.py
from accounts.forms import StaffRegistrationForm
from django.contrib.messages.api import error
import business
from services.models import Category
from business import forms
from django.core.exceptions import ValidationError
from business.models import Amenities, Business, PaymentMethods, Photos, Service, Staff, StaffService
from django.db.models.expressions import F
from business.forms import BusinessAmenitiesForm, BusinessPaymentMethodsForm, BusinessPhotosForm, BusinessProfileForm, BusinessServiceForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

def dashboard(request):
    context = {'page_title':'Business Dashboard'}
    return render(request,'business/dashboard.html',context);

@login_required(login_url = "login")
def profile(request):
    user = request.user.id
    bus_count =Business.objects.filter(user_id=user).count();
    bus = Business.objects.filter(user_id=user).first()
    if bus_count == 0:
        form = BusinessProfileForm()
    else:
        form = BusinessProfileForm(instance=bus)
    if request.method == 'POST':
        form = BusinessProfileForm(request.POST)
        if form.is_valid:
            if(bus_count <1):
                form = form.save(commit=False)
                form.user_id = user
                form.save()
                messages.success(request,'business profile added successfully')
                return redirect('bus.profile')
            else:
                form = BusinessProfileForm(request.POST,instance=bus) 
                form.save()
                messages.success(request,'business profile updated successfully')
                return render(request,'business/profile.html',{'form': form})
    
    context = {'page_title':'Business Profile','form':form}
    return render(request,'business/profile.html',context);

def options(request,type='all'):
    user = request.user.id
    business = Business.objects.filter(user_id=user).first()
    amenities = Amenities.objects.filter(business_id = business.id)
    amenities_count = amenities.count()
    payment_methods = PaymentMethods.objects.filter(business_id = business.id)
    payment_methods_count = payment_methods.count()
    if request.method =='POST':
        if type =='amenities':
            form = BusinessAmenitiesForm(request.POST)
            if form.is_valid:
                if(amenities_count == 0 ):
                    form = form.save(commit=False)
                    form.business_id = business.id
                    form.save()
                    messages.success(request,'your business amenities are added successfully')
                    return redirect('bus.options')
                else:
                    amenity = amenities.first()
                    amenity.cus_parking = request.POST.get('cus_parking','off')
                    amenity.card_accept = request.POST.get('card_accept','off')
                    amenity.child_friendly = request.POST.get('child_friendly','off')
                    amenity.disability = request.POST.get('disability','off')
                    amenity.wifi = request.POST.get('wifi','off')
                    amenity.loyalty_program = request.POST.get('loyalty_program','off')
                    amenity.pet_friendly = request.POST.get('pet_friendly','off')
                    amenity.save()
                    messages.success(request,'your business amenities are updated')
                    return redirect('bus.options')
        elif type == 'payment_methods':
            form = BusinessPaymentMethodsForm(request.POST)
            if form.is_valid:
                if payment_methods_count == 0 :
                    form = form.save(commit=False)
                    form.business_id = business.id
                    form.save()
                    messages.success(request,'your payment methods are added successfully')
                    return redirect('bus.options')
                else:
                    method = payment_methods.first()
                    method.cash = request.POST.get('cash','off')
                    method.physical = request.POST.get('physical','off')
                    method.check = request.POST.get('check','off')
                    method.paypal = request.POST.get('paypal','off')
                    method.gift_card = request.POST.get('gift_card','off')
                    method.bank_transfer = request.POST.get('bank_transfer','off')
                    method.save()
                    messages.success(request,'your business payment methods are updated')
                    return redirect('bus.options')
    context = {'page_title':'Business Options','amenities':amenities.first(),'payment_methods':payment_methods.first()}
    return render(request,'business/options.html',context)

def photos(request):
    user = request.user.id
    bus_photos=[]
    business = Business.objects.filter(user_id=user).first()
    bus_photos_2 = Photos.objects.filter(business_id=business.id)
    bus_photos_count = bus_photos_2.count()
    if bus_photos_count > 0 :
        bus_photos = Photos.objects.get(business_id=business.id)
    if request.method =='POST':
        if bus_photos_count > 0:
            form = BusinessPhotosForm(request.POST,request.FILES, instance=bus_photos)
        if bus_photos_count == 0:
            form = BusinessPhotosForm(request.POST,request.FILES)
        if form.is_valid:
            print(form.clean)
            if bus_photos_count == 0:
                form = form.save(commit=False)
                form.business_id = business.id
            form.save()
            messages.success(request,'your photo uploaded successfully')
            return redirect('bus.photos')
    context = {'page_title':'Business Photos','photos':bus_photos}
    return render(request, 'business/photos.html',context)

def services(request,pk=''):
    form = BusinessServiceForm()
    user = request.user.id
    business = Business.objects.filter(user_id=user).first()
    categories = Category.objects.all()
    if request.method =='POST':
        form = BusinessServiceForm(request.POST)
        form_service =request.POST.get('service')
        bus_services = Service.objects.filter(service_id=form_service)
        if bus_services.count() < 1:
            if form.is_valid():
                form = form.save(commit=False)
                form.business_id = business.id
                form.save()
                messages.success(request,'service added to your profile')
                BusinessServiceForm()
                return redirect('bus.services')
            else:
                messages.error(request,'form not correctly filled')
        else:
            messages.error(request,'ERROR: selected service already added to your profile')
    context = {'page_title':'Business Services','form':form,'categories':categories,'business':business,'error':error}
    return render(request,'business/services.html',context)

def updateService(request,pk):
    service = Service.objects.get(id=pk)
    if request.method =='POST':
        form = BusinessServiceForm(request.POST,instance=service)
        print(form)
        if form.is_valid():
            form.save()
            messages.success(request,'service updated')
            return redirect('bus.services')
    return redirect('bus.services')
def deleteService(request,pk):
    service = Service.objects.get(id=pk)
    if request.method =='POST':
        service.delete()
        messages.success(request,'service removed from your profile')
    return redirect('bus.services')
def staff(request):
    user = request.user.id
    biz = Business.objects.filter(user_id=user).first()
    bus_services = Service.objects.filter(business_id=biz.id)
    form = StaffRegistrationForm()
    if request.method=='POST':
        form = StaffRegistrationForm(request.POST,request.FILES)
        if form.is_valid():
            instance_account = form.save()
            staff = Staff.objects.create(user=instance_account,business=biz)
            staff.save()
            services = request.POST.getlist('service')
            for service in services:
                staffService = StaffService.objects.create(staff=staff,service_id= service,is_active=True)
                staffService.save()
            messages.success(request,'Staff added successfully')
            return redirect('bus.staff')
    context ={'page_title':'Business Staff','services':bus_services,'form':form,'business':biz}
    return render(request,'business/staff.html',context)
def deleteStaff(request):
    return render(request,'business/staff.html')
def updateStaff(request):
    return render(request,'business/staff.html')

business/templates/business/dashboard.html
{%extends 'main-bus.html'%}
{%load static%}
{%block content%}

{%endblock%}

business/templates/business/options.html
{%extends 'main-bus.html'%}
{%load static}
{%block content%}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Manage Your Business Profile</h4>
                <p class="card-title-desc">Let your customers know about your business,provide contact, location and social media details</p>
                {%include 'alert.html'%}
        
                <div class="row">
                    <div class="col-xl-4">
                        <!-- <h5 class="font-size-16 mb-4">General Info</h5> -->
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title mb-3">Amenities</h4>        
                                <form action="{%url 'bus.options' 'amenities'%}" class="bus-form" method="POST">
                                    {%csrf_token%}
                                    <div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="cus_parking" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.cus_parking 'on' %} checked {%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Customer Parking</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="card_accept" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.card_accept 'on'%}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Card Accepted</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="disability" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.disability 'on'%}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Disability Accessible</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="child_friendly" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.child_friendly 'on'%}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Child-Friendly</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="pet_friendly" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.pet_friendly 'on'%}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Pet Friendly</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="wifi" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.wifi 'on'%}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">WiFi</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="loyalty_program" class="form-check-input" id="customSwitchsizelg" {%ifequal amenities.loyalty_program 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Loyalty Program</label>
                                        </div>
                                    </div>
                                    <div class="mt-4">
                                        <a href="javascript:void(0)"  style="width: fit-content;" onclick="bus.submitForm(this);" class="btn btn-primary btn-center btn-rounded w-md cus_submit">Update Amenities</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4">
                    </div>
                    <div class="col-xl-4">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title mb-3">Payment Methods</h4>        
                                <form action="{%url 'bus.options' 'payment_methods'%}" class="bus-form" method="POST">
                                    {%csrf_token%}
                                    <div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="cash" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.cash 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Cash</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="physical" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.physical 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Physical Card Terminal</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="check" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.check 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Check</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="paypal" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.paypal 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">PayPal</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="bank_transfer" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.bank_transfer 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Bank Transfer</label>
                                        </div>
                                        <div class="form-check form-switch form-switch-lg mb-3" dir="ltr">
                                            <input type="checkbox" name="gift_card" class="form-check-input" id="customSwitchsizelg" {%ifequal payment_methods.gift_card 'on' %}checked{%endifequal%}>
                                            <label class="form-check-label" for="customSwitchsizelg">Gift Card</label>
                                        </div>
                                    </div>
                                    <div class="mt-4 ">
                                        <a href="javascript:void(0)"  style="width: fit-content;" onclick="bus.submitForm(this);" class="btn btn-primary btn-center btn-rounded w-md cus_submit">Update Payment Methods</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

business/templates/business/staff.html
{%extends 'main-bus.html'%}
{%load static%}
{%block content%}


<div class="row mb-4">
    <div class="col-lg-12">
        {%include 'alert.html'%}
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add A Staff</h4>
                <p class="card-title-desc">Let your customers know what the services you offer and how you charge!</p>
                <form action="{%url 'bus.staff'%}" method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="row">
                                <label class="form-label">Personal Details</label>
                                <div class="col-lg-12 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Full Name</label>
                                        <input type="text" placeholder="e.g John Doe" class="form-control" name="full_name" >
                                    
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-6">
                                    <div class="mb-3">
                                        <label class="form-label">E-mail</label>
                                        <input type="text" placeholder="e.g j.doe@example.com" class="form-control" name="email" >
                                        {{form.email.errors}}
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-6">
                                    <div class="mb-3">
                                        <label class="form-label">Nickname</label>
                                        <input type="text" placeholder="e.g stylishJoe" class="form-control" name="username" >
                                        {{form.username.errors}}
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-6">
                                    <div class="mb-3">
                                        <label class="form-label">Password</label>
                                        <input type="password" placeholder="**********" class="form-control" name="password1" >
                                        {{form.password1.errors}}
                                    </div>
                                </div>
                                <div class="col-lg-6 col-sm-6">
                                    <div class="mb-3">
                                        <label class="form-label">Re-Password</label>
                                        <input type="password" placeholder="**********" class="form-control" name="password2" >
                                    </div>
                                </div>
                                <div class="col-lg-12 col-sm-12">
                                    <div class="mb-3">
                                        <label class="form-label">Profile Photo</label>
                                        <input type="file" class="form-control" name="photo" >
                                        {{form.username.errors}}
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Services Offered</label>
                                    <select class="form-control select2 select2-multiple" name="service" select2-multiple" multiple="multiple" data-placeholder="Choose ..." required>                      
                                        {% for service in services %}
                                            <optgroup label="{{category.name}}">
                                                <option value="{{service.id}}">{{service.service.name}}</option>
                                            </optgroup>
                                        {% endfor%}
                                    </select>
                                    {{form.service.errors}}
                                </div>
                                <div class="col-lg-12">
                                    <div class="mb-3">
                                        <a href="javascript:void(0);" class="btn btn-success waves-effect waves-light" onclick="bus.submitForm(this)" >Add New Staff</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                
            </div>
        </div>
        <!-- end select2 -->
    </div>
    <div class="col-lg-8">
        <div class="row">
            {%for staff in business.staff_set.all%}
            <div class="col-xl-3 col-sm-6">
                <div class="card text-center">
                    <div class="card-body">
                        <div class="dropdown float-end">
                            <a class="text-body dropdown-toggle font-size-16" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="uil uil-ellipsis-h"></i>
                            </a>
                          
                            <div class="dropdown-menu dropdown-menu-end" style="">
                                <a class="dropdown-item" href="#">Remove</a>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="mb-4">
                            <img src="{%static 'images_/users/avatar-2.jpg'%}" alt="" class="avatar-lg rounded-circle img-thumbnail">
                        </div>
                        <h5 class="font-size-16 mb-1"><a href="#" class="text-dark">{{staff.user.full_name}}</a></h5>
                        <!-- <p class="text-muted mb-2">Full Stack Developer</p> -->
                        
                    </div>

                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-outline-light text-truncate"><i class="uil uil-search-alt me-1"></i> Services</button>

                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>
{%endblock%}